### ISSUE TITLE
Implement IBM CI/CD pipeline for kogito-runtimes

### ISSUE THREAD

**Issue by baldimir** [IBM/kie-roadmap#1]
There needs to be an IBM build pipeline based on One Pipeline templates for kogito-runtimes. 

Acceptance criteria: 
- ~~Pipeline exists in the IBM Cloud environment under BAMOE account.~~
- ~~[It is possible to update versions of the produced artifacts](https://github.com/IBM/kie-roadmap/issues/26)~~
- ~~[It is possible to upload the built jars to a Maven repository](https://github.com/IBM/kie-roadmap/issues/28)~~
- [The jars built are signed](https://github.com/IBM/kie-roadmap/issues/30) 
- [Required security scans are executed and results of these scans are stored in repositories defined for this data](https://github.com/IBM/kie-roadmap/issues/34)

**Comment by baldimir** [comment]
Some of the things in acceptance criteria are not clear yet, those need to be updated, when we have more information and decisions about those topics are made. E.g. what should be the artifact repository, etc.

**Comment by porcelli** [comment]
what about kogito-apps?

**Comment by baldimir** [comment]
Yes, please feel free to create such issues for cicd if I miss something.

**Comment by baldimir** [comment]
This will be split into individual issues.

**Comment by baldimir** [comment]
I am closing this as it is hard to always update this to track the current status. Please use the label area:cicd to get information about the current status.
