### ISSUE TITLE
Filter out unneeded examples from kogito-examples product zip

### ISSUE THREAD

**Issue by baldimir** [IBM/kie-roadmap#104]
For 9.0, we don't need all [kogito-examples](https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples) in the product zip. Filter out all examples that are not needed. Current examples that should be included are these Quarkus examples: 

- org.kie.kogito.examples:decisiontable-quarkus-example
- org.kie.kogito.examples:dmn-drools-quarkus-metrics
- org.kie.kogito.examples:dmn-event-driven-quarkus
- org.kie.kogito.examples:dmn-knative-quickstart-quarkus
- org.kie.kogito.examples:dmn-listener-quarkus 
- org.kie.kogito.examples:dmn-listener-dtable
- org.kie.kogito.examples:dmn-quarkus-example
- org.kie.kogito.examples:kogito-travel-agency-example
    - org.kie.kogito.examples:kogito-travel-agency-example-basic
- org.kie.kogito.examples:process-business-rules-quarkus
- org.kie.kogito.examples:process-decisions-quarkus
- org.kie.kogito.examples:process-decisions-rest-quarkus
- org.kie.kogito.examples:process-decisions-rules-quarkus
- org.kie.kogito.examples:process-error-handling
- org.kie.kogito.examples:rules-legacy-quarkus-example
- org.kie.kogito.examples:rules-quarkus-helloworld
- org.kie.kogito.examples:ruleunit-event-driven-quarkus
- org.kie.kogito.examples:ruleunit-quarkus-example

Acceptance criteria: 
- kogito-examples product zip contains only specified examples.

**Comment by baldimir** [comment]
@porcelli @martinweiler @tiagobento @LightGuard please review the list and comment what should be removed.

**Comment by baldimir** [comment]
There is a script in our automation that builds product zips - product-binaries.sh. This script contains functions to build each zip. One of the functions builds the zip for kogito-examples. It does it by cloning the repository and zipping it. There needs to be added commands to delete the unnecessary examples.

**Comment by baldimir** [comment]
@inodeman I updated the list of examples in the description.

**Comment by baldimir** [comment]
@inodeman I created the branch, because I needed the alignment for [another issue](https://github.com/IBM/kie-roadmap/issues/106). The branch is in the internal mirror and it is called bamoe-9.0. 

To resolve this issue, it is needed to make sure the branch is used in the zip build and verifying that the contents of the zip match the branch. To configure the branch, please change the property kogito-examples-branch in the publishing pipeline. If you need more information, please let me know. I can explain how the publishing pipeline works.

**Comment by inodeman** [comment]
Tested with logs on the publish pipeline, and I can see only the files needed 
<img width="834" alt="image" src="https://github.com/IBM/kie-roadmap/assets/39567766/85fae165-faf4-4a96-980d-80ccca5a71d8">
