### ISSUE TITLE
Build only necessary modules in kogito-apps build

### ISSUE THREAD

**Issue by jstastny-cz** [IBM/kie-roadmap#114]
Build only required modules in kogito-apps build. The build can be restricted by using -pl parameter of Maven, e.g. mvn clean install -pl 'org.kie.kogito:someartifactid'.

Modules that need to be built: 
- jit-executor (the parent with submodules)
- runtime-tools-quarkus-extension (the parent with submodules)

Acceptance criteria: 
- Only specified modules are built during kogito-apps build.

**Comment by baldimir** [comment]
PR merged.
