### ISSUE TITLE
Build customized kie-sandbox image

### ISSUE THREAD

**Issue by jstastny-cz** [IBM/kie-roadmap#135]
To build customized kie-sandbox image we need to create a custom dockerfile which extends on the regular kie-sandbox image and sets required env variables pointing at customized graphics and override naming.

**Comment by jstastny-cz** [comment]
After the community changes are in and images released, the following would be a way to override app name and icons being used:
```
FROM --platform=linux/amd64 quay.io/kie-tools/kie-sandbox-image:latest

ENV KIE_SANDBOX_APP_NAME 'Customized-name'

COPY logo_reverse.svg /var/www/html/images/app_logo_rgb_fullcolor_reverse.svg
COPY logo_default.svg /var/www/html/images/app_logo_rgb_fullcolor_default.svg
COPY favicon.svg /var/www/html/favicon.svg

EXPOSE 8080

ENTRYPOINT [ "/kie-sandbox/entrypoint.sh" ]
```

**Comment by tiagobento** [comment]
Just for reference, we also need to update the `KIE_SANDBOX_EDITORS` variable to remove PMML.

I think also that `KIE_SANDBOX_REQUIRE_CUSTOM_COMMIT_MESSAGE` should be set to `true`.

And `KIE_SANDBOX_ACCELERATORS` needs to point to https://github.com/ibm/bamoe-canvas-quarkus-accelerator

**Comment by tiagobento** [comment]
It might also be a good idea to delete the PMML-related static resources from the image.
