### ISSUE TITLE
Automate the build of BAMOE Canvas image

### ISSUE THREAD

**Issue by baldimir** [IBM/kie-roadmap#138]
We have a branded BAMOE Canvas image (branded KIE Sandbox image) here: https://github.com/IBM/bamoe/tree/main/images/bamoe-canvas. The build and upload to Quay.io needs to be automated. 

Acceptance criteria: 
- The image si built during the publishing pipeline run. 
- The image is uploaded to Quay.io, [into bamoe-canvas repository](https://quay.io/repository/bamoe/bamoe-canvas), as part of the build in publishing pipeline.

**Comment by jstastny-cz** [comment]
This one is tackled under #135 with one difference, the image will be available under quay.io/bamoe/canvas instaed of the proposed repository in description.
