### ISSUE TITLE
Add Descriptions to BAMOE images on Quay.io

### ISSUE THREAD

**Issue by tiagobento** [IBM/kie-roadmap#164]
There are three images published to Quay.io as part of BAMOE, but they currently do not have a proper Description on the page.

We need to copy the contents of the README.md files we have for each image and get it to the "Description" section somehow. See:
1. https://quay.io/repository/bamoe/canvas
2. https://quay.io/repository/bamoe/extended-services
3. https://quay.io/repository/bamoe/git-cors-proxy

We need to update the documentation pointing to the image's "main page" on Quay.io so that users can see the README there.

**Comment by jstastny-cz** [comment]
As far as I can tell, the description is a rich text text field ... so this task is more about providing correct content manually there.

**Comment by jstastny-cz** [comment]
Ah, there could be 3rd party tool for that, see https://poweruser.blog/pushing-a-readme-file-to-docker-hub-68200bc4bf71

**Comment by tiagobento** [comment]
Done manually for 9.0.0.
