### ISSUE TITLE
Dynamic Workflow Engine capabilities analysis (v7)

### ISSUE THREAD

**Issue by porcelli** [IBM/kie-roadmap#20]
We an assessment of the impact required in the engine in order to be able to advance the existing dynamic capabilities of the workflow. It's expected an assessment for short, mid and longer term.

**Comment by elguardian** [comment]
added Dynamic Workflow Engine capabilities analysisin v7.pdf to the shared folder.

**Comment by baldimir** [comment]
Closing this as the analysis is done.
