### ISSUE TITLE
Prepare a CI/CD script for updating version of NPM projects

### ISSUE THREAD

**Issue by baldimir** [IBM/kie-roadmap#27]
We want to be able to have our own IBM versions of our NPM projects. For that, we need to be able to update version of those projects.

We have a scripts folder in the inernal bamoe-ci repository. Write and add a script that updates version. 

Please follow classis pull request process with the internal CI repository. (Fork, do changes on a branch, submit a PR)

**Comment by jstastny-cz** [comment]
kie-tools has already scripts for the actual version update. After cloning the repo it's enough to call:
```
pnpm bootstrap
pnpm update-version-to XY-version-0
```

**Comment by jstastny-cz** [comment]
The tool used previously is under kiegroup https://github.com/kiegroup/npm-treatment-tool .

**Comment by jstastny-cz** [comment]
The outcome was to use a separate line of versioning, making it enough to run the `bootstrap` and `update-version-to` scripts already present in kie-tools.

**Comment by tiagobento** [comment]
@jstastny-cz Sorry for not having seen this before. Do you still need input from me?
