### ISSUE TITLE
Analyze current status of Kogito straight-through processing

### ISSUE THREAD

**Issue by baldimir** [IBM/kie-roadmap#3]
Kogito straight-through processing was late in development in Red Hat. We need to find out what is the current status, gaps etc. 

Acceptance criteria: 
- Document describing the current status exists. 
- Issues for the identified gaps are created in kie-roadmap or kie-issues repository.

**Comment by baldimir** [comment]
BAPL from Red Hat JIRA is here: https://issues.redhat.com/browse/BAPL-1944

**Comment by baldimir** [comment]
[Kogito straight-through processes status.xlsx](https://github.com/IBM/kie-roadmap/files/9990141/Kogito.straight-through.processes.status.xlsx)

**Comment by baldimir** [comment]
Very basic status of the issues listed in the Epic linked in the previous comment: 

[Kogito STP status.xlsx](https://github.com/IBM/kie-roadmap/files/10011110/Kogito.STP.status.xlsx)

**Comment by jstastny-cz** [comment]
Collecting information in [Kogito STP - current state](https://ibm-my.sharepoint.com/:w:/r/personal/tibor_zimanyi_ibm_com/Documents/Business%20Automation%20Open%20Edition/Kogito%20STP%20-%20current%20state.docx?d=w36ccf502411746f19d57d01c4b353f57&csf=1&web=1&e=FQP5VA)
