### ISSUE TITLE
Sign built NPM artifacts

### ISSUE THREAD

**Issue by baldimir** [IBM/kie-roadmap#31]
Using the recommended way how to sign NPM artifacts, automate the signing of those artifacts from CI/CD builds. Create a script or similar that could be reused in multiple repositories and place it to the bamoe-ci repository.

**Comment by tiagobento** [comment]
I may be wrong, but for product, we won't have NPM artifacts published, only images.. Am I missing something?

**Comment by baldimir** [comment]
Moving this back to Backlog

**Comment by baldimir** [comment]
If you think this can be closed, please feel free to do so.

**Comment by baldimir** [comment]
Closing this as the product artifacts are only container images.
