### ISSUE TITLE
Fix unit tests in kogito-runtimes pipeline

### ISSUE THREAD

**Issue by gitgabrio** [IBM/kie-roadmap#48]
Currently, unit test execution in `kogito-runtime` ci pipeline (`code-unit-tests` step) is broken due to `Docker` requirement.
`Docker` should be altready available, though.
Verify:

1.  Docker is actually up and running and available at that step
2. verify configuration to make use of it

**Comment by baldimir** [comment]
I added -Dproductized to the run, which ignores unnecessary integration-tests during unit-test run and ignored 2 more integration tests modules. The test run is green locally for me now. Running it in the pipeline.

**Comment by baldimir** [comment]
Done. Merged.
