### ISSUE TITLE
Write BAMOE documentation for 9.0.0

### ISSUE THREAD

**Issue by tiagobento** [IBM/kie-roadmap#54]
Proposed Table of contents:

1. Intro
2. Runtimes and Tools
3. Kogito and Drools
  3.1. Intro
  3.2. Maven configuration
  3.3. Reference architecture for Business Automation projects
4. KIE Sandbox
  4.1. Intro
  4.2. Working with Git on KIE Sandbox
  4.3. Authenticating with external services on KIE Sandbox
  4.3. Working with Cloud providers on KIE Sandbox
  4.5. File management on KIE Sandbox
  4.6. Technicalities of KIE Sandbox
  4.7. Business Automation projects on KIE Sandbox
  4.8. Deploying your own KIE Sandbox
5. VS Code Extensions
  5.1. Intro
  5.2. DMN
  5.2. BPMN
6. Standalone Editors
  6.1. Intro
  6.2. Examples
7. Tutorials

**Comment by tiagobento** [comment]
@LightGuard @porcelli Can you please take a look at my proposal? I don't expect I covered everything, but I tried to layout a "format" that we could follow, dividing the docs by features on the subsections...

**Comment by LightGuard** [comment]
@tiagobento are you looking at this being the reference documentation? I would argue for a different order based on how a user interacts with the system.

**Comment by LightGuard** [comment]
Much of this has actually been done. I'm looking for help with some of the other sections, people have been contacted. If you're interested in helping, please comment here so we can keep everything centralized.

**Comment by tiagobento** [comment]
@LightGuard Done? :D
