### ISSUE TITLE
Security scan: code-dynamic-scan in kogito-apps pipeline

### ISSUE THREAD

**Issue by gitgabrio** [IBM/kie-roadmap#70]
Implement the `code-dynamic-scan` inside kogito-apps pipeline.
The `ci-pipeline` is made of a series of step.
They are implemented/defined inside `.pipeline-config-kogito-runtimes.yaml`

Scope of this ticket is to:

1. analyze how to define the `code-dynamic-scan` step
2. review what has to be implemented, and what is not require
3. provide actual implementations

Possible source of documentation could be:

1. one-pipeline/docs
2. https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-getting-started&pos=2
3. https://cloud.ibm.com/docs/devsecops?topic=devsecops-cd-devsecops-ci-pipeline#devsecops-ci-pipeline-dynamic-codescan

For the moment being, that dynamic scan should be executed only on the jit-executor module, since it exposes some rest services used bye kie-tools

**Comment by jstastny-cz** [comment]
Will be mostly around ZAP scans: https://cloud.ibm.com/docs/devsecops?topic=devsecops-zap-scans
