### ISSUE TITLE
Create BAMOE 9.0 BOM

### ISSUE THREAD

**Issue by porcelli** [IBM/kie-roadmap#74]

**Comment by baldimir** [comment]
Initial version drafted here: https://github.com/baldimir/bamoe-maven/blob/initial-changes/bamoe-bom/pom.xml. I tried to remove as much as I knew, however I expect there are more things possible to remove. @porcelli @tiagobento could you please review and let me know?

**Comment by martinweiler** [comment]
Is the intent to define the versions for all supported artifacts (similar to what we had [in v7](https://github.com/jboss-integration/rhba-boms/tree/main/ba-platform-bom))? If yes, shouldn't we remove some of the jBPM / process related dependencies at least for the 9.0 release?

**Comment by porcelli** [comment]
@martinweiler some jBPM needs to stay, as 9.0 has STP support for Rules Orchestration. We also want to provide the Dev UI for the enhanced STP dev experience.

**Comment by porcelli** [comment]
@baldimir maybe open a PR so it's easier to comment on individual dependencies:)

**Comment by baldimir** [comment]
Yes, agree, I will create a PR. I was thinking first to not do PR for visibility reasons, but why not.

**Comment by baldimir** [comment]
PR is here https://github.com/IBM/bamoe-maven/pull/1

**Comment by baldimir** [comment]
First version merged. Not closing this as it still needs some review. Will do that as part of another PR.

**Comment by baldimir** [comment]
@porcelli @tiagobento @martinweiler could you please do a final review of [the bom](https://github.com/IBM/bamoe/blob/main/runtime-libraries/bamoe-bom/pom.xml)?
What needs to be done: 
- Final [review of commits](https://github.com/IBM/bamoe/commits/main) that I did to delete things from the bom -> Making sure I didn't delete what should be in the bom.
- Final [review of the bom](https://github.com/IBM/bamoe/blob/main/runtime-libraries/bamoe-bom/pom.xml) -> Checking if something needs to be deleted.

**Comment by baldimir** [comment]
Based on conversation with Alex, we need to have all our jars listed in the bom, not relying on getting them transitively from Kogito artifacts that are already in the bom.

**Comment by baldimir** [comment]
PRs merged. Closing this.
