### ISSUE TITLE
Implement build-containerize in kie-tools pipeline

### ISSUE THREAD

**Issue by gitgabrio** [IBM/kie-roadmap#81]
Create sandbox image in kie-tools pipeline
All required variables should be declared as "Environment properties" in ui, and should be documented

**Comment by baldimir** [comment]
Current problem being solved is that by default, the images build is implemented to use podman to build the images. However we don't have podman available in the environment, we have Docker.

**Comment by jstastny-cz** [comment]
Is there something pending after #36 or can this be resolved together with it?
